services:
  frontend:
    image: 'ghcr.io/romtomgreat/film-react-nest_frontend:latest'
    container_name: frontend_container
    env_file:
      - frontend/.env
    volumes:
      - frontend_build:/app/dist

  backend:
    image: 'ghcr.io/romtomgreat/film-react-nest_backend:latest'
    container_name: backend_container
    env_file:
      - backend/.env
    ports:
      - 3000:3000
    depends_on:
      - database
    networks:
      - webnet

  database:
    image: postgres:16.4
    container_name: postgres_container
    env_file:
      - backend/.env
    volumes:
      - ./docker-init.sql:/docker-entrypoint-initdb.d/docker-init.sql
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - webnet

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    env_file:
      - backend/.env
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - 8080:80
    depends_on:
      - database
    restart: always
    networks:
      - webnet

  nginx:
    image: nginx
    container_name: nginx_container
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - frontend_build:/var/www/frontend:ro
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/letsencrypt/:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - frontend
      - backend
    restart: always
    networks:
      - webnet

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    networks:
      - webnet

volumes:
  db_data:
  pgadmin-data:
  frontend_build:

networks:
  webnet: