services:
  frontend:
    image: 'ghcr.io/romtomgreat/film-react-nest_frontend:latest'
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    environment:
      VITE_API_URL: /api/afisha
      VITE_CDN_URL: /content/afisha
    volumes:
      - frontend_build:/app/dist

  backend:
    image: 'ghcr.io/romtomgreat/film-react-nest_backend:latest'
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      DEBUG: ${DEBUG}
      DATABASE_DRIVER: ${DATABASE_DRIVER}
      DATABASE_URL: 'postgres://database:5432/${DB_NAME}'
      DATABASE_USERNAME: ${DB_USER}
      DATABASE_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3000:3000
    depends_on:
      - database
    networks:
      - webnet

  database:
    image: postgres:16.4
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker-init.sql:/docker-entrypoint-initdb.d/docker-init.sql
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - webnet

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - 8080:80
    restart: always
    networks:
      - webnet

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - frontend_build:/var/www/frontend:ro
    ports:
      - 81:80
      - 443:443
    depends_on:
      - frontend
      - backend
    restart: always
    networks:
      - webnet

volumes:
  db_data:
  pgadmin-data:
  frontend_build:

networks:
  webnet: