name: CI

env:
  REGISTRY: ghcr.io

on:
  push:
    branches:
      - main
      - review_2
  pull_request:
    branches:
      - main
      - review_2

jobs: 
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - name: Set Lower Case for Owner
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'

      - run: |
          echo "repo ${OWNER_LC}"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to the DockerHub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: '${{ env.REGISTRY }}/$${{ env.REPO }}/film-react-nest_backend:latest'

      - name: Build and push Front Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: '${{ env.REGISTRY }}/${{ env.REPO }}/film-react-nest_frontend:latest'

      - name: Build and push Nginx Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./nginx
          file: ./nginx/Dockerfile
          push: true
          tags: '${{ env.REGISTRY }}/${{ env.REPO }}/film-react-nest_nginx:latest'